### ISSUE TITLE
Improve "No field with id" error message

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#993]
![image](https://user-images.githubusercontent.com/1780597/31854732-6af097ce-b69e-11e7-993c-005d38c06d4d.png)

### Current Behaviour

Not helpful error is returned you refer to a specific field in a permission and remove it from `types.graphql`.

### Reproduction

```graphql
type User @model {
  id: ID! @isUnique
  description: String!
  name: String!
  age: Int!
}
```

```yml
permissions:
  - operation: User.read
  - fields: [name, description]
```

Remove the `description: String!` field from `types.graphql`, but still refer to it in the permission:

```graphql
type User @model {
  id: ID! @isUnique
  name: String!
  age: Int!
}
```

```yml
permissions:
  - operation: User.read
  - fields: [name, description]
```

```
graphcool deploy
```

Results in above error message.

### Expected Behaviour

Something like this:

> User
>   You are about to remove the field 'description: String!', but are still referencing it from a permission.

**Comment by marktani** [comment]
![image](https://user-images.githubusercontent.com/1780597/31854757-b2d81e22-b69e-11e7-8216-e3d8fcd7a7bf.png)

**Comment by marktani** [comment]
Interestingly enough, when deploying the same definition to a new target, you get a better/different error message:

![image](https://user-images.githubusercontent.com/1780597/31854894-668f7518-b6a0-11e7-972c-c2076ee52590.png)

**Comment by kimf** [comment]
I ran into this when removing a field and then deploying while having this in my graphcool.yml
```
permissions:
- operation: "*"
```

**Comment by marktani** [comment]
Interesting, were you able to resolve this?

**Comment by kimf** [comment]
Fortunately enough I didn't have any data yet in that local deploy, so I just create a new one.

**Comment by lolcoolkat** [comment]
Just ran into this error :( What I had to do was edit my types.graphql file first... and add/remove the field, then run "graphcool deploy". After deploying I added/removed the same field in my graphcool.yml file.. and BAM! it works :) 

For some reason trying to remove both of the fields at the same time..resulted in the error stated in this thread. 

Hope this helps anyone else. But would love for this error to be more specific about which operation the field is associated with 👍

**Comment by jvbianchi** [comment]
I just ran into this error: https://www.graph.cool/forum/t/no-field-with-id-xxxxxx-project-id/1415

**Comment by crubier** [comment]
I just ran into the same problem... Nuked the DB and created a new one... Couldn't find any other solution

**Comment by marktani** [comment]
Hey @crubier:

> Couldn't find any other solution

Did you try removing all references to fields that you deleted but that were still mentioned in permissions?

**Comment by mwickett** [comment]
I'm having this issue. I was able to deploy our development environment by removing any field specific restrictions in my `graphcool.yml` file, deploying with the fields removed from `types.graphql`, then uncommenting my field specific permission restrictions and deploying again. 

But I can't do this easily for two other environments.

**Comment by marktani** [comment]
You don't need to remove _every_ field specific restrictions. In the reproduction example in my original example, it's sufficient to update the permission from
```yml
permissions:
  - operation: User.read
  - fields: [name, description]
```

to

```yml
permissions:
  - operation: User.read
  - fields: [name]
```

That is, removing the reference to the deleted field `description`.

**Comment by marktani** [comment]
This has been fixed in 0.9 🎉

**Comment by wasd171** [comment]
@marktani unfortunately I am still getting this cryptic error (not sure that the reason is the same though) with `graphcool@0.9`

**Comment by kbrandwijk** [comment]
@wasd171 As this was a server-side fix, could you elaborate when you are getting it. In a local deployment, or a shared cluster deployment? Did you update your local docker images after upgrading to 0.9, by either doing `graphcool local pull`, or `graphcool local up` _after_ the upgrade?

**Comment by wasd171** [comment]
@kbrandwijk I experienced it on shared cluster. Actually I even erased all my data and was still unable to deploy, I had to delete the service and create a new one

**Comment by marktani** [comment]
@wasd171, do you receive this error message after following the _exact_ reproduction steps outlined in the OP? If not, please open a new bug report describing how you can reproduce it.

Also see https://github.com/graphcool/framework/issues/1231 for another occurence of the  "No field with id" error message, that's unrelated to the one discussed in the current thread.

**Comment by marktani** [comment]
> Actually I even erased all my data and was still unable to deploy

Note that this error is unrelated to the _data_ in your service. The error message indicates that some field was deleted from your DB, but is still referenced elsewhere.

**Comment by kimf** [comment]
Same thing here, issue still exists. 
My guess is that my wildcard created a lot of permission fields and when removing a field, the update command can’t find the deletion in the diff before applying.
